// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var LogCtrl;

  LogCtrl = (function() {
    LogCtrl.$inject = ['$scope', 'airportsService'];

    function LogCtrl(scope, airportsService) {
      this.scope = scope;
      this.airportsService = airportsService;
      this.scope.airports = ['lfpz', 'lfyr', 'lyjh'];
      this.scope.steps = [
        {
          airport: 'lfpz',
          comment: ''
        }, {
          airport: 'lfyr',
          comment: 'stop here'
        }
      ];
      this.scope.$watch('airport', function(airport) {
        return console.log(airport);
      });
    }

    return LogCtrl;

  })();
  return angular.module('flightPlanApp').controller('LogCtrl', LogCtrl);
})();
