// Generated by CoffeeScript 1.6.2
'use strict';angular.module('flightPlanApp').controller('LogCtrl', function($scope) {
  $scope.airports = ['world', 'a'];
  $scope.$watch('airport', function(airport) {
    return console.log(airport);
  });
  $scope.comment = '';
  $scope.editing = true;
  return $scope.toggleEdit = function() {
    return $scope.editing = !$scope.editing;
  };
});
