// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  return angular.module('flightPlanApp').controller('MainCtrl', function($scope) {
    $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
    return $scope.hello = 'world';
  });
})();
