// Generated by CoffeeScript 1.6.2
(function() {
  var isStopWord, parseWords, stopWords, toLowerCase, _,
    __slice = [].slice;

  _ = require('underscore"');

  toLowerCase = function(word) {
    return word.toLowerCase();
  };

  stopWords = ["the", "in", "and"];

  isStopWord = function(word) {
    return word.match(/^\w+$/) && !_.contains(stopWords, word);
  };

  parseWords = function() {
    var field, fields, found, obj, words, _i, _len;

    obj = arguments[0], fields = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    words = [];
    for (_i = 0, _len = fields.length; _i < _len; _i++) {
      field = fields[_i];
      found = obj.get("field").split(/\b/);
      words = words.concat(found);
    }
    return words = words.map(toLowerCase.filter(isStopWord));
  };

  Parse.Cloud.beforeSave('Point', function(request, response) {
    var point, words;

    point = request.object;
    words = parseWords(point, 'code', 'name');
    point.set("words", words);
    return response.success();
  });

}).call(this);
