// Generated by CoffeeScript 1.7.1
'use strict';
Parse.Cloud.job('updatePoints', function(request, status) {
  var query;
  Parse.Cloud.useMasterKey();
  query = new Parse.Query('Point');
  return query.each(function(point) {
    return point.save();
  }).then(function() {
    return status.success('Migration completed successfully');
  }, function(error) {
    return status.error('Oups' + error);
  });
});
