// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var Airport, AirportService, PointsService;

  Airport = (function() {
    function Airport() {}

    return Airport;

  })();
  AirportService = (function() {
    function AirportService() {}

    return AirportService;

  })();
  PointsService = (function() {
    function PointsService() {}

    PointsService.prototype.all = function() {};

    return PointsService;

  })();
  return angular.module('flightPlanApp').factory('airportsService', AirportService);
})();
