// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var Airport, AirportService;

  Airport = (function() {
    function Airport() {}

    return Airport;

  })();
  AirportService = (function() {
    function AirportService() {}

    return AirportService;

  })();
  return angular.module('flightPlanApp').factory('airportsService', AirportService);
})();
