// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var Point, PointsService;

  Point = (function() {
    function Point(data) {
      angular.copy(data, this);
    }

    return Point;

  })();
  PointsService = (function() {
    function PointsService($resource) {
      this._res = $resource('https://api.parse.com/1/classes/Points', {}, {
        method: 'GET',
        headers: {
          'X-Parse-Application-Id': 'IKEiwnzgURrngabC1gxIZFF5O0jPfz0D1DzWjsHO',
          'X-Parse-REST-API-Key': 'dCHVZQBmSm1FcYLI3KSHC4YwRSWoT5sh6I33wfD4'
        }
      });
    }

    PointsService.prototype.all = function() {
      return this._res.query();
    };

    PointsService.prototype.get = function(code) {};

    return PointsService;

  })();
  PointsService.$inject = ['$resource'];
  return angular.module('flightPlanApp').service('pointsService', PointsService);
})();
