// Generated by CoffeeScript 1.6.2
'use strict';angular.module('flightPlanApp', ['ngCookies', 'ngResource', 'ngSanitize', 'ngRoute', 'ui.select2', 'btford.markdown']).config(function($routeProvider) {
  return $routeProvider.when('/', {
    templateUrl: 'views/main.html',
    controller: 'MainCtrl'
  }).when('/log', {
    templateUrl: 'views/log.html',
    controller: 'LogCtrl'
  }).otherwise({
    redirectTo: '/'
  });
});
