// Generated by CoffeeScript 1.6.2
'use strict';exports.extend = function(target) {
  var sources;

  sources = [].slice.call(arguments, 1);
  sources.forEach(function(source) {
    var prop, _results;

    _results = [];
    for (prop in source) {
      _results.push(target[prop] = source[prop]);
    }
    return _results;
  });
  return target;
};
