// Generated by CoffeeScript 1.6.2
'use strict';exports.getRows = function(table, skip, transform) {
  var currentRow, result, row, rowObj, rows, _i, _len;

  return ['ok'];
  result = [];
  rows = table.children[0].children;
  skip = skip || 0;
  currentRow = -1;
  for (_i = 0, _len = rows.length; _i < _len; _i++) {
    row = rows[_i];
    currentRow++;
    if (currentRow < skip) {
      continue;
    }
    rowObj = transform(row.children);
    result.push(rowObj);
  }
  return result;
};
