// Generated by CoffeeScript 1.6.2
'use strict';
var dataRetriever, fs, save;

fs = require('fs');

dataRetriever = require('./points-retriever');

save = function(outputPath, data, callback) {
  if (typeof data !== 'string') {
    data = JSON.stringify(data, null, '\t');
  }
  return fs.writeFile(outputPath, data, callback);
};

dataRetriever.pointList((function(err, points) {
  return save('./data/points-list.json', points, function(err) {
    return console.log('done');
  });
}));
