// Generated by CoffeeScript 1.6.2
'use strict';
var fs, helpers, pointRetriever, pointsRetriever, readPoints, save;

fs = require('fs');

pointsRetriever = require('./points-repo-local');

pointRetriever = require('./point-repo-local');

helpers = require('./helpers');

readPoints = function(points, current, next) {
  var point;

  if (current === points.length) {
    return next();
  }
  point = points[current];
  return pointRetriever.getPoint(point, function(err, pointDetail) {
    if (err) {
      console.log(err);
      return readPoints(points, ++current, next);
    }
    helpers.extend(point, pointDetail);
    return readPoints(points, ++current, next);
  });
};

save = function(points, callback) {
  var data;

  if (typeof points !== 'string') {
    data = JSON.stringify(points, null, '\t');
  }
  return fs.writeFile('./data/points-merged.json', data, callback);
};

pointsRetriever.pointList(function(err, points) {
  if (err) {
    return console.log(err);
  }
  return readPoints(points, 0, function() {
    if (err) {
      return console.log(err);
    }
    return save(points, function() {
      if (err) {
        return console.log(err);
      }
      return console.log('success');
    });
  });
});
