// Generated by CoffeeScript 1.6.2
'use strict';angular.module('flightPlanApp', []).directive('logstep', function() {
  alert('ok');
  return {
    restrict: 'E',
    scope: {},
    templateUrl: '/Scripts/app/partials/CategoryComponent.html',
    controller: function($scope, $attrs) {
      alert('ok');
      $scope.airports = ['world', 'a'];
      $scope.$watch('airport', function(airport) {
        return console.log(airport);
      });
      $scope.comment = '';
      $scope.editing = true;
      return $scope.toggleEdit = function() {
        return $scope.editing = !$scope.editing;
      };
    }
  };
});
