// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  return angular.module('flightPlanApp').directive('logstep', function() {
    return {
      restrict: 'E',
      scope: {
        airports: '=',
        airport: '=',
        comment: '='
      },
      templateUrl: 'scripts/directives/logstep.html',
      controller: function($scope, $attrs) {
        $scope.$watch('[comment, editing]', function() {
          return $scope.showCommentLabel = $scope.comment !== '' || $scope.editing;
        }, true);
        $scope.editing = false;
        return $scope.toggleEdit = function() {
          return $scope.editing = !$scope.editing;
        };
      }
    };
  });
})();
